#!/usr/bin/env bash

. "$HOME/.cache/wal/colors.sh"

OFFSET_X=12
OFFSET_Y=62

# Obter largura da tela ativa
SCREEN_WIDTH=$(xrandr | awk '/\*/ {print $1}' | head -n1 | cut -d'x' -f1)

# Calcular largura do menu
MENU_WIDTH=$((SCREEN_WIDTH - (2 * OFFSET_X)))
# MENU_WIDTH=$(( SCREEN_WIDTH / 3 ))

clipmenu -i -l 8 \
    -x "$OFFSET_X" \
    -y "$OFFSET_Y" \
    -z "$MENU_WIDTH" \
    -sf "$background" \
    -nb "$background" \
    -sb "$foreground"

