[global/wm]
include-file = ~/.config/polybar/grayblocks/colors.ini

[bar/dock]
enable-ipc = true

width = ${env:DOCK_WIDTH:520}
height = 36
offset-x = ${env:DOCK_X:0}
offset-y = 16
fixed-center = true

background = ${color.background}
foreground = ${color.foreground} 

radius = 0
line-size = 0

module-margin-left = 3

border-bottom-size = 10
border-top-size = 10
border-color = ${color.background}

; wm-restack = bspwm
override-redirect = true

font-0 = "Iosevka:style=Medium:size=15;2"
font-1 = "Symbols Nerd Font:size=14;3"

modules-center = term files browser code spotify

bottom = true

; dim-value = 0.0

[module/apps]
type = custom/text
content-background = ${color.background-alt}
content-foreground = ${color.foreground}
content-overline = ${color.background}
content-underline = ${color.background}
content-padding = 1

[module/term]
inherit = module/apps
content = 
click-left = alacritty

[module/files]
inherit = module/apps
content = 
click-left = thunar

[module/browser]
inherit = module/apps
content = 
click-left = firefox

[module/code]
inherit = module/apps
content = 
click-left = code

[module/spotify]
inherit = module/apps
content = 
click-left = spotify
